it("Возводит x в степень n", function() {
  let x = 5;

  let result = x;
  assert.equal(pow(x, 1), result);

  result *= x;
  assert.equal(pow(x, 2), result);

  result *= x;
  assert.equal(pow(x, 3), result);
});


Ответ: 

Три теста написаны в одной функции,
если произойдёт ошибка в начале,
остальные проверки не пройдут.
Необходимо разбить тест на несколько блоков it.